# dag_eng:
#   target: dev
#   outputs:
#     dev:
#       type: sqlserver
#       driver: 'ODBC Driver 17 for SQL Server' # (The ODBC Driver installed on your system)
#       server: localhost
#       port: 1433
#       database: ENGINEERING 
#       schema: dbo
#       user: sa
#       password: K@roukazeno1
#       trust_cert: True

dag_eng:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/Users/mac/Desktop/Analytics_Enginerring/dagster-dbt/.env/dag_eng/engineering.duckdb'
      threads: 24


dag_sqlserver:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: localhost
      port: 1433
      database: YOUR_DATABASE_NAME
      schema: dbo
      user: your_user
      password: your_password
      trust_cert: True


