name: CI

on:
  push: 
    branches: [ data ]
  pull_request: 
    branches: [ data ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List all files 
        run: ls 

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: python .env/fin_proj/create_file.py


      - name: List all files 
        run: ls 

     
    
